### ISSUE TITLE
remove dependency on go-multistore

### ISSUE THREAD

**Issue by raulk** [filecoin-project/go-commp-utils#4]
This is used rather awkwardly and without much necessity. The caller should be responsible for passing the right blockstore, whether it comes from a multistore or not.

**Comment by raulk** [comment]
Looks like only go-fil-markets uses it, not even Lotus itself.

https://pkg.go.dev/github.com/filecoin-project/go-commp-utils@v0.1.1/pieceio?tab=importedby

![image](https://user-images.githubusercontent.com/1101242/126372965-5f270bb4-475d-4707-9814-6ff7b920dbc6.png)

**Comment by ribasushi** [comment]
This seems to have been resolved some time in the past: https://pkg.go.dev/github.com/filecoin-project/go-commp-utils@v0.1.5-0.20240802040721-f1a31a6d3384?tab=imports
